### ISSUE TITLE
Digilent Nexys Video program stuck at __rt_event_execute

### ISSUE THREAD

**Issue by bbo49** [pulp-platform/pulpissimo#130]
Hi,

Currently I'm evaluating the pulpissimo environment on a Digilent Nexys Video board. After building and programming the bitstream using the scripts, I was able to run the hello world example under pulp-rt-examples/hello.

After the hello example I tried to run some of the examples on the other interfaces on the platform, but I'm facing issues.

When I run the GPIO output example under pultp-rt-examples/gpio/output, I change the GPIO to 5 (SPIM CS1, as can be found in the pad_frame.v) because LED0 of the fpga board is connected to this pin by the default configuration.
After running the example I don't see the LED blinking, I also tried to increase the delay too 500 ms in case the blink would be to fast, without success.

As a second test, I tried to test the SPI master with the example under pulp-rt-examples/periph/spim/send. By default this example uses CS1. When I run this example I can see LED0(CS1) going low, however it doesn't come back on again. When I interrupt with CTRL-C in GDB, I get:
```
Program received signal SIGINT, Interrupt.
__rt_event_execute (sched=<optimized out>, sched@entry=0x0, wait=wait@entry=1)
    at kernel/events.c:200
200	      rt_irq_enable();
```
A stack trace is added below:
```
#0  __rt_event_execute (sched=<optimized out>, sched@entry=0x0, 
    wait=wait@entry=1) at kernel/events.c:200
#1  0x1c0092ce in __rt_wait_event (event=event@entry=0x1c0011e8)
    at kernel/events.c:250
#2  0x1c008722 in __rt_wait_event_check (call_event=<optimized out>, 
    event=0x0)
    at /home/pulp/pulp/pulp-sdk/pkg/sdk/dev/install/include/rt/rt_event.h:351
#3  __rt_spim_send (handle=handle@entry=0x1c001278, data=<optimized out>, 
    len=len@entry=128, qspi=qspi@entry=0, 
    cs_mode=cs_mode@entry=RT_SPIM_CS_AUTO, event=event@entry=0x0)
    at drivers_deprecated/spim/spim-v3.c:263
#4  0x1c0083f6 in rt_spim_send (event=0x0, mode=RT_SPIM_CS_AUTO, len=128, 
    data=<optimized out>, handle=0x1c001278)
    at /home/pulp/pulp/pulp-sdk/pkg/sdk/dev/install/include/rt/rt_spim.h:343
#5  main () at test.c:45
```

As a third test, I tried to run the I2S example, when running this example, the following is printed on the serial console:
```
Entering main controller
[RT(31,0)] WARNING: [I2S] Failed to open i2s device
```

Am I missing something for running programs or accessing interfaces on this FPGA target?
Edit: I'm currently setting up the simulation platform again, to run the examples and compare the outputs. 

My setup:
OS: Ubuntu 18.04.4 LTS
Vivado Version: 2018.2
Pulpissimo commit: 8584e684efb19074ab22bcbe35dc75542fde047b
pulp-sdk   commit: 69db0f108b53e83b8ba853d9c418d17d03bd300f

For configuring the toolchain I used the instructions on https://github.com/pulp-platform/pulp-riscv-
gnu-toolchain
```
Installation (Pulp)
./configure --prefix=/opt/riscv --with-arch=rv32imc --with-cmodel=medlow --enable-multilib
make
```

For building the SDK I used:
```
source configs/fpgas/pulpissimo/genesys2.sh ( As I read in other posts and documentation, all the FPGA platforms use the genesys2.sh file)
source configs/platform-fpga.sh 
make all
source pkg/sdk/dev/sourceme.sh
```

**Comment by bbo49** [comment]
After checking with the rtl simulation platform it turned out that the ```pulp-rt-examples/gpio/output``` example is not controlling the ```pad_mux_i``` signal in ```pad_control.v```
After adding the following lines to the C-code I can see the LED0 connected spim_csn1 blinking on the FPGA board:
```
volatile unsigned int* PAD_MUX_ADDR = 0x1A104010;
*PAD_MUX_ADDR = 0x400;
```

I also tried running the ```pulp-rt-examples/periph/spim/send``` example inside the simulation environment. The program doesn't get stuck here, and I see CSN1 going low followed by clocks and data, and CSN1 going high again. I still need to check if the data coming out is correct.

It looks like something goes wrong when implementing the design in the FPGA board.

**Comment by bbo49** [comment]
Closing as I can't reproduce the issue of the SPI example getting stuck in the FPGA after rebuilding the bitstream.
